import { API_BASE_URL } from '../../apiConfig';
// ============================================================================
// FILE: src/components/roadmap/CareerInput.jsx
// PURPOSE: DB-Driven Career Selection (FR4.1)
// ============================================================================

import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext'; 

const CareerInput = ({ onCareerSelect }) => {
  const { user } = useAuth();
  const [careerId, setCareerId] = useState('');
  const [dbCareers, setDbCareers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [enrolling, setEnrolling] = useState(false);

  // Fetch available careers generated by the Admin
  useEffect(() => {
    const fetchCareers = async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/api/careers`);
        const data = await response.json();
        if (data.success) {
          setDbCareers(data.careers);
        }
      } catch (err) {
        console.error("Error fetching careers:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchCareers();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!careerId || !user) return;
    
    setEnrolling(true);
    try {
      // Enroll the user in the database
      await fetch(`${API_BASE_URL}/api/enroll`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: user.user_id, career_id: parseInt(careerId) })
      });
      
      // Tell App.jsx to switch to the roadmap view
      onCareerSelect(parseInt(careerId));
    } catch (err) {
      console.error("Enrollment failed:", err);
      setEnrolling(false);
    }
  };

  return (
    <div style={{ maxWidth: '600px', margin: '0 auto', padding: '40px 20px' }}>
      <div style={{ textAlign: 'center', marginBottom: '40px' }}>
        <h2 style={{ fontSize: '32px', color: '#111827', margin: '0 0 15px 0', fontFamily: "'Aeonik', 'Plus Jakarta Sans', sans-serif" }}>
          Define Your Tech Career
        </h2>
        <p style={{ color: '#4b5563', fontSize: '16px', lineHeight: '1.6' }}>
          Select a career path below to access industry-standard learning modules, curated resources, and certification exams verified by FSKTM UM.
        </p>
      </div>

      <div style={{ backgroundColor: 'white', padding: '30px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)' }}>
        <form onSubmit={handleSubmit}>
          <div style={{ marginBottom: '25px' }}>
            <label style={{ display: 'block', marginBottom: '10px', fontWeight: 'bold', color: '#374151' }}>
              I want to become a...
            </label>
            
            <select
              value={careerId}
              onChange={(e) => setCareerId(e.target.value)}
              style={{ width: '100%', padding: '14px', borderRadius: '8px', border: '1px solid #d1d5db', backgroundColor: 'white', fontSize: '15px', cursor: 'pointer' }}
              disabled={loading || enrolling}
            >
              <option value="">
                {loading ? "Loading available careers..." : "-- Select a Career --"}
              </option>
              {dbCareers.map((c) => (
                <option key={c.career_id} value={c.career_id}>{c.career_name}</option>
              ))}
            </select>
          </div>

          <button 
            type="submit" 
            style={{ 
              width: '100%', padding: '16px', borderRadius: '8px', border: 'none', color: 'white', fontSize: '16px', fontWeight: 'bold',
              backgroundColor: (!careerId || enrolling) ? '#9ca3af' : '#4c2882',
              cursor: (!careerId || enrolling) ? 'not-allowed' : 'pointer'
            }}
            disabled={!careerId || enrolling}
          >
            {enrolling ? 'Enrolling & Loading Path...' : 'Start Learning Journey 🚀'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default CareerInput;