create table public.career (
  career_id serial not null,
  career_name text not null,
  description text null,
  constraint career_pkey primary key (career_id)
) TABLESPACE pg_default;

create table public.learning_resource (
  resource_id serial not null,
  skill_id integer null,
  title text not null,
  provider text null,
  cost_type text null,
  url text null,
  constraint learning_resource_pkey primary key (resource_id),
  constraint learning_resource_skill_id_fkey foreign KEY (skill_id) references skill (skill_id),
  constraint learning_resource_cost_type_check check (
    (
      cost_type = any (array['free'::text, 'paid'::text])
    )
  )
) TABLESPACE pg_default;

create table public.progress_record (
  progress_id bigint generated by default as identity not null,
  user_id uuid null,
  step_id bigint null,
  completion_status text null,
  completion_date timestamp with time zone null default now(),
  constraint progress_record_pkey primary key (progress_id),
  constraint progress_record_step_id_fkey foreign KEY (step_id) references roadmap_step (step_id),
  constraint progress_record_user_id_fkey foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;

create table public.progress_record (
  progress_id bigint generated by default as identity not null,
  user_id uuid null,
  step_id bigint null,
  completion_status text null,
  completion_date timestamp with time zone null default now(),
  constraint progress_record_pkey primary key (progress_id),
  constraint progress_record_step_id_fkey foreign KEY (step_id) references roadmap_step (step_id),
  constraint progress_record_user_id_fkey foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;

create table public.quiz_result (
  result_id bigint generated by default as identity not null,
  user_id uuid null,
  skill_id bigint null,
  score integer null,
  attempt_date timestamp with time zone null default now(),
  constraint quiz_result_pkey primary key (result_id),
  constraint quiz_result_skill_id_fkey foreign KEY (skill_id) references skill (skill_id),
  constraint quiz_result_user_id_fkey foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;

create table public.quiz_result (
  result_id bigint generated by default as identity not null,
  user_id uuid null,
  skill_id bigint null,
  score integer null,
  attempt_date timestamp with time zone null default now(),
  constraint quiz_result_pkey primary key (result_id),
  constraint quiz_result_skill_id_fkey foreign KEY (skill_id) references skill (skill_id),
  constraint quiz_result_user_id_fkey foreign KEY (user_id) references users (user_id) on delete CASCADE
) TABLESPACE pg_default;

create table public.roadmap_step (
  step_id serial not null,
  career_id integer null,
  skill_id integer null,
  step_order integer not null,
  constraint roadmap_step_pkey primary key (step_id),
  constraint roadmap_step_career_id_fkey foreign KEY (career_id) references career (career_id),
  constraint roadmap_step_skill_id_fkey foreign KEY (skill_id) references skill (skill_id)
) TABLESPACE pg_default;

create table public.skill (
  skill_id serial not null,
  skill_name text not null,
  skill_category text null,
  description text null,
  constraint skill_pkey primary key (skill_id)
) TABLESPACE pg_default;

create table public.users (
  user_id uuid not null,
  name text null,
  email text null,
  role text null,
  programme text null,
  academic_year text null,
  graduation_year text null,
  created_at timestamp with time zone null default now(),
  constraint users_pkey primary key (user_id),
  constraint users_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;